nallo=nallo256;
nallosub=rawsubsample(nallo);
subplot(1,3,1)
showgrey(nallosub)
nallosub2=rawsubsample(nallosub);
subplot(1,3,2)
showgrey(nallosub2)
nallosub3=rawsubsample(nallosub2);
subplot(1,3,3)
showgrey(nallosub3)